name: Request Merchandise
description: Here you request NeoNephos merchandise.
title: "[Request]: Merchandise"
labels: ["outreach-topic"]

body:
  - type: markdown
    attributes:
      value: |
        Use this form to request NeoNephos Merchandise.
        All submitted requests will be reviewed by the Outreach Committee.

  - type: textarea
    id: requestor-name
    attributes:
      label: Name
      description: What is your name? Please use a real identifier in lieu of nicknames.
    validations:
      required: true

  - type: textarea
    id: requestor-contact
    attributes:
      label: Contact
      description: How can we get in touch with you? List your e-mail and other preferred communication.
    validations:
      required: true

  - type: textarea
    id: requestor-affiliations
    attributes:
      label: Project Affiliations
      description: If you are affiliated with one of our projects, please name it here.
    validations:
      required: false

  - type: dropdown
    id: location
    attributes:
      label: Shipping Location
      description: Where should the merchandise be sent to? The location for self pickup is in Walldorf, Germany.
      options:
        - "Within the European Union or United Kingdom."
        - "North America."
        - "Other"
        - "I pick it up myself."
  - type: dropdown
    id: item-1
    attributes:
      label: Merchandise Item #1
      description: Select the first item you want.
      options:
        - "T-Shirt"
        - "Baseball Cap"
        - "Sticker"
        - "None"

  - type: dropdown
    id: item-1-qty
    attributes:
      label: Quantity for Item #1
      options:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"

  - type: dropdown
    id: item-2
    attributes:
      label: Merchandise Item #2
      description: Select the second item you want.
      options:
        - "T-Shirt"
        - "Baseball Cap"
        - "Sticker"
        - "None"

  - type: dropdown
    id: item-2-qty
    attributes:
      label: Quantity for Item #2
      options:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
  - type: textarea
    id: requestor-merchandise-reasoning
    attributes:
      label: Purpose
      description: Why do you need the merchandise (e.g. for a specific event).
    validations:
      required: true
