---
name: Request Merchandise
description: Here you request NeoNephos merchandise.
title: "[Request]: Merchandise"
labels:
  - outreach-topic
assignees:
  - banannadreams
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request NeoNephos Merchandise.
        All submitted requests will be reviewed by the Outreach Committee.
  - type: textarea
    id: requestor-name
    attributes:
      label: Name
      description: What is your name? Please use a real identifier in lieu of nicknames.
    validations:
      required: true
  - type: textarea
    id: requestor-contact
    attributes:
      label: Contact
      description: How can we get in touch with you? List your e-mail and other
        preferred communication.
    validations:
      required: true
  - type: textarea
    id: requestor-affiliations
    attributes:
      label: Project Affiliations
      description: If you are affiliated with one of our projects, please name it here.
    validations:
      required: false
  - type: dropdown
    id: location
    attributes:
      label: Shipping Location
      description: Where should the merchandise be sent to? The location for self
        pickup is in Walldorf, Germany.
      options:
        - Within the European Union or United Kingdom.
        - North America.
        - Other
        - I pick it up myself.
  - type: dropdown
    id: requested-items
    attributes:
      label: Requested Merchandise
      description: Select all items you want to request. Multi-select possible. See
        more details about the items
        [here](../../topics/merch/inventory/inventory.csv).
      multiple: true
      options:
        - NeoNephos T-Shirts
        - NeoNephos Hoodies
        - NeoNephos Stickers
        - NeoNephos Flyers
        - Platform Mesh Stickers
  - type: dropdown
    id: requested-items-amount
    attributes:
      label: How many do you need?
      description: "How many items do you need per category? Note: For items with
        various sizes like T-Shirts, you will be asked to specify which sizes
        you need later."
      multiple: true
      options:
        - 10 per selected item
        - 20 per selected item
        - 50 per selected item
        - 100 per selected item
        - Other
  - type: textarea
    id: requestor-merchandise-reasoning
    attributes:
      label: Purpose
      description: Why do you need the merchandise (e.g. for a specific event).
    validations:
      required: true
