name: Handle Merchandise Request

on:
  issues:
    types: [opened]

jobs:
  move-issue-to-pr:
    if: "${{ contains(github.event.issue.title, 'Merchandise') }}"
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Update merchandise inventory file
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const inventoryFile = 'topics/merch/inventory/stock_of_nonallocated_merchandise.csv';

            fs.appendFileSync(
              inventoryFile,
              `\n<<< IF REQUEST #${context.issue.number} APPROVED, INSERT UPDATED MERCH FIGURES HERE >>>`
            );

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "merch-request-${{ github.event.issue.number }}"
          commit-message: "Add merchandise request from Issue #${{ github.event.issue.number }}"
          title: "${{ github.event.issue.title }}"
          body: "This PR has been created from the merchandise request from issue #${{ github.event.issue.number }}. Requestor: An Outreach Committee team member will get in touch with you."
          base: main
          assignees: banannadreams

      - name: Comment and close issue
        uses: actions/github-script@v7
        with:
          script: |
            const prUrl = "${{ steps.cpr.outputs.pull-request-url }}";
            const issueNumber = context.issue.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `Your request has been moved to ${prUrl}.`
            });

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: 'closed',
              state_reason: 'completed'
            });
